name: CI

permissions:
  contents: read

'on':
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-sec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest bandit

      - name: Run unit tests
        env:
          PYTHONPATH: .
        run: |
          pytest -q

      - name: Run Bandit security checks
        run: |
          bandit -q -r . -x .venv,venv,__pycache__ -s B101

